version: '2.2'
services:
  web:
    image: aspendigital/octobercms:latest
    ports:
      - 8088:80
    volumes:
      - $PWD:/var/www/html/plugins/aspendigital/resizer
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql #DB_HOST should match the service name of the database container
      - DB_DATABASE=octobercms
      - DB_USERNAME=root
      - DB_PASSWORD=root

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=octobercms