version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=octobercms

  web:
    image: aspendigital/octobercms:latest
    ports:
      - 8088:80
    volumes:
      - $PWD:/var/www/html
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_DATABASE=octobercms
      - DB_USERNAME=root
      - DB_PASSWORD=root
      -
    depends_on:
      - mysql