version: '2.1'
services:
  app:
    build:
      context: ./docker/app
    image: asgardcms/app:latest
    ports:
      - 8089:80
      - 443:443
    volumes:
      - .:/var/www/html:cached
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_CACHE=false
      - INSTALLED=true
      - APP_KEY=base64:ASFALWYzJGoZK5TUZImj5pFPjBEu4xTiTCkW93DBQdc=
      - APP_URL=http://localhost:8089
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=asgardcms
      - DB_USERNAME=homestead
      - DB_PASSWORD=secret
      - CACHE_DRIVER=array
      - TRANSLATIONS_CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_DRIVER=sync
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - MAIL_DRIVER=smtp
      - MAIL_HOST=mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_FROM_ADDRESS=null
      - MAIL_FROM_NAME=null
      - MAIL_ENCRYPTION=null

    networks:
      - asgard_net
  redis:
    build:
      context: ./docker/redis
    image: asgardcms/redis:latest
    volumes:
      - redisdata:/data
    networks:
      - asgard_net

  mysql:
    build:
      context: ./docker/mysql
    image: asgardcms/mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: asgardcms
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - asgard_net

  node:
    build:
      context: ./docker/node
    image: asgardcms/node:latest
    volumes:
      - .:/var/www/html

  blackfire:
    image: blackfire/blackfire
    environment:
      BLACKFIRE_SERVER_ID:
      BLACKFIRE_SERVER_TOKEN:
    networks:
      - asgard_net

volumes:
  redisdata:
    driver: local
  mysqldata:
    driver: local

networks:
  asgard_net:
    driver: bridge
